package enums;

import lombok.Getter;

public enum MonsterType {
    ACORNBEARER("ACORNBEARER", 2, 1, 1, Rarity.COMMON),
    ARANASI_BROODMOTHER("ARANASI_BROODMOTHER", 4, 6, 6, Rarity.COMMON),
    ARCANE_FLETCHER("ARCANE_FLETCHER", 2, 3, 2, Rarity.COMMON),
    ARCANE_SERVANT("ARCANE_SERVANT", 2, 3, 2, Rarity.COMMON),
    ARCANE_WATCHER("ARCANE_WATCHER", 5, 6, 3, Rarity.RARE),
    ARCH_VILLAIN_RAFAAM("ARCH_VILLAIN_RAFAAM", 7, 8, 7, Rarity.LEGENDARY),
    ARCHIVIST_ELYSIANA("ARCHIVIST_ELYSIANA", 7, 7, 9, Rarity.LEGENDARY),
    ARCHMAGE_VARGOTH("ARCHMAGE_VARGOTH", 2, 6, 4, Rarity.LEGENDARY),
    AZERITE_ELEMENTAL("AZERITE_ELEMENTAL", 2, 7, 5, Rarity.EPIC),
    BARISTA_LYNCHEN("BARISTA_LYNCHEN", 4, 5, 5, Rarity.LEGENDARY),
    BATTERHEAD("BATTERHEAD", 3, 12, 8, Rarity.EPIC),
    BIG_BAD_ARCHMAGE("BIG_BAD_ARCHMAGE", 6, 6, 10, Rarity.EPIC),
    BLASTMASTER_BOOM("BLASTMASTER_BOOM", 7, 7, 7, Rarity.RARE),
    BRONZE_HERALD("BRONZE_HERALD", 3, 2, 3, Rarity.COMMON),
    BURLY_SHOVELFIST("BURLY_SHOVELFIST", 9, 9, 9, Rarity.COMMON),
    CATRINA_MEURTE("CATRINA_MEURTE", 6, 8, 8, Rarity.LEGENDARY),
    CHEF_NOMI("CHEF_NOMI", 6, 6, 7, Rarity.LEGENDARY),
    CLOCKWORK_GOBLIN("CLOCKWORK_GOBLIN", 3, 3, 3, Rarity.RARE),
    COMMANDER_RHYSSA("COMMANDER_RHYSSA", 4, 3, 3, Rarity.LEGENDARY),
    CONVINCING_INFILTRATOR("CONVINCING_INFILTRATOR", 2, 6, 5, Rarity.RARE),
    CRYSTAL_STAG("CRYSTAL_STAG", 4, 4, 5, Rarity.EPIC),
    DALARAN_CRUSADER("DALARAN_CRUSADER", 5, 4, 5, Rarity.COMMON),
    DALARAN_LIBRARIA("DALARAN_LIBRARIA", 2, 3, 2, Rarity.COMMON),
    DRAGON_SPEAKER("DRAGON_SPEAKER", 3, 5, 5, Rarity.EPIC),
    EAGER_UNDERLIN("EAGER_UNDERLIN", 2, 2, 4, Rarity.RARE),
    ECCENTRIC_SCRIBE("ECCENTRIC_SCRIBE", 6, 4, 6, Rarity.COMMON),
    EVIL_CABLE_RAT("EVIL_CABLE_RAT", 1, 1, 2, Rarity.COMMON),
    EVIL_CONSCRIPTER("EVIL_CONSCRIPTER", 2, 2, 2, Rarity.COMMON),
    EVIL_GENIUS("EVIL_GENIUS", 2, 2, 2, Rarity.COMMON),
    EVIL_MISCREANT("EVIL_MISCREANT", 1, 4, 3, Rarity.COMMON),
    EXOTIC_MOUNTSELLER("EXOTIC_MOUNTSELLER", 5, 8, 7, Rarity.RARE),
    FACELESS_RAGER("FACELESS_RAGER", 5, 1, 3, Rarity.COMMON),
    FEL_LORD_BETRUG("FEL_LORD_BETRUG", 5, 7, 8, Rarity.LEGENDARY),
    FLIGHT_MASTER("FLIGHT_MASTER", 3, 4, 3, Rarity.COMMON),
    HECKLEBOT("HECKLEBOT", 3, 8, 4, Rarity.RARE),
    HEISTBARON_TOGWAGGLE("HEISTBARON_TOGWAGGLE", 5, 5, 6, Rarity.LEGENDARY),
    HENCH_CLAN_BURGLAR("HENCH_CLAN_BURGLAR", 4, 3, 4, Rarity.COMMON),
    HENCH_CLAN_HAG("HENCH_CLAN_HAG", 3, 3, 4, Rarity.EPIC),
    HENCH_CLAN_HOGSTEED("HENCH_CLAN_HOGSTEED", 2, 1, 2, Rarity.COMMON),
    HENCH_CLAN_SHADEQUILL("HENCH_CLAN_SHADEQUILL", 4, 7, 4, Rarity.COMMON),
    HENCH_CLAN_SNEAK("HENCH_CLAN_SNEAK", 3, 3, 3, Rarity.COMMON),
    HEROIC_INNKEEPER("HEROIC_INNKEEPER", 4, 4, 8, Rarity.COMMON),
    JEPETTO_JOYBUZZ("JEPETTO_JOYBUZZ", 6, 6, 8, Rarity.LEGENDARY),
    JUMBO_IMP("JUMBO_IMP", 8, 8, 10, Rarity.EPIC),
    KALECGOS("KALECGOS", 4, 12, 10, Rarity.LEGENDARY),
    KEEPER_STALLADRIS("KEEPER_STALLADRIS", 2, 3, 2, Rarity.LEGENDARY),
    KHADGAR("KHADGAR", 2, 2, 2, Rarity.LEGENDARY),
    KIRIN_TOR_TRICASTER("KIRIN_TOR_TRICASTER", 3, 3, 4, Rarity.RARE),
    LIFEWEAVER("LIFEWEAVER", 2, 5, 3, Rarity.RARE),
    LUCENTBARK("LUCENTBARK", 4, 8, 8, Rarity.LEGENDARY),
    MAD_SUMMONER("MAD_SUMMONER", 4, 4, 6, Rarity.RARE),
    MADAME_LAZUR("MADAME_LAZUR", 3, 2, 3, Rarity.LEGENDARY),
    MAGIC_CARPET("MAGIC_CARPET", 1, 6, 3, Rarity.EPIC),
    MAGIC_DART_FROG("MAGIC_DART_FROG", 1, 3, 2, Rarity.COMMON),
    MANA_CYCLONE("MANA_CYCLONE", 2, 2, 2, Rarity.EPIC),
    MANA_RESERVOIR("MANA_RESERVOIR", 0, 6, 2, Rarity.COMMON),
    MESSENGER_RAVEN("MESSENGER_RAVEN", 3, 2, 3, Rarity.COMMON),
    MUCHMORPHER("MUCHMORPHER", 4, 4, 5, Rarity.EPIC),
    NOZARI("NOZARI", 4, 12, 10, Rarity.LEGENDARY),
    OBLIVITRON("OBLIVITRON", 3, 4, 6, Rarity.LEGENDARY),
    OMEGA_DEVASTATOR("OMEGA_DEVASTATOR", 4, 5, 4, Rarity.EPIC),
    PORTAL_KEPPER("PORTAL_KEPPER", 5, 2, 4, Rarity.RARE),
    PORTAL_OVERFIEND("PORTAL_OVERFIEND", 5, 6, 6, Rarity.EPIC),
    POTION_VENDOR("POTION_VENDOR", 1, 1, 1, Rarity.COMMON),
    PROUD_DEFENDER("PROUD_DEFENDER", 2, 6, 4, Rarity.COMMON),
    RECURRING_VILAIN("RECURRING_VILAIN", 3, 6, 5, Rarity.RARE),
    SAFEGUARD("SAFEGUARD", 4, 5, 6, Rarity.COMMON),
    SCARGIL("SCARGIL", 4, 4, 4, Rarity.LEGENDARY),
    SHADOWY_FIGURE("SHADOWY_FIGURE", 2, 2, 2, Rarity.EPIC),
    SHIMMERFLY("SHIMMERFLY", 1, 1, 1, Rarity.RARE),
    SLUDGE_SLUPER("SLUDGE_SLUPER", 2, 1, 1, Rarity.RARE),
    SOLDIER_OF_FORTUNE("SOLDIER_OF_FORTUNE", 5, 6, 4, Rarity.COMMON),
    SPELLBOOK_BINDER("SPELLBOOK_BINDER", 3, 2, 2, Rarity.COMMON),
    SPELLWARD_JEWELER("SPELLWARD_JEWELER", 3, 4, 3, Rarity.RARE),
    SUNREAVER_SPY("SUNREAVER_SPY", 2, 3, 2, Rarity.COMMON),
    SUNREAVER_WARMAGE("SUNREAVER_WARMAGE", 4, 4, 5, Rarity.RARE),
    SWAMPQUEEN_HAGATHA("SWAMPQUEEN_HAGATHA", 5, 5, 7, Rarity.LEGENDARY),
    TAK_NOZWISKER("TAK_NOZWISKER", 6, 6, 7, Rarity.LEGENDARY),
    THE_BOOM_REAVER("THE_BOOM_REAVER", 7, 9, 10, Rarity.LEGENDARY),
    TOXFIN("TOXFIN", 1, 2, 1, Rarity.COMMON),
    TRAVELING_HEALER("TRAVELING_HEALER", 3, 2, 4, Rarity.COMMON),
    TUNNEL_BLASTER("TUNNEL_BLASTER", 3, 7, 7, Rarity.RARE),
    UNDERBELLY_ANGLER("UNDERBELLY_ANGLER", 2, 3, 2, Rarity.RARE),
    UNDERBELLY_FENCE("UNDERBELLY_FENCE", 2, 3, 2, Rarity.RARE),
    UNDERBELLY_OOZO("UNDERBELLY_OOZO", 3, 5, 7, Rarity.RARE),
    UNSEEN_SABOTEUR("UNSEEN_SABOTEUR", 5, 6, 6, Rarity.EPIC),
    URSATRON("URSATRON", 3, 3, 3, Rarity.COMMON),
    VEREESA_WINDRUNNER("VEREESA_WINDRUNNER", 5, 6, 7, Rarity.LEGENDARY),
    VICIOUS_SCRAPHOUND("VICIOUS_SCRAPHOUND", 2, 2, 2, Rarity.COMMON),
    VIOLET_SPELLSWORD("VIOLET_SPELLSWORD", 1, 6, 4, Rarity.COMMON),
    VIOLET_WARDEN("VIOLET_WARDEN", 4, 7, 6, Rarity.COMMON),
    WALKING_FOUNTAIN("WALKING_FOUNTAIN", 4, 8, 8, Rarity.COMMON),
    WHIRLWIND_TEMPEST("WHIRLWIND_TEMPEST", 6, 6, 8, Rarity.EPIC),
    ZAYLE_SHADOW_CLOAK("ZAYLE_SHADOW_CLOAK", 3, 2, 2, Rarity.LEGENDARY);

    @Getter
    private String name;
    @Getter
    private int damage;
    @Getter
    private int health;
    @Getter
    private int mana;
    @Getter
    private Rarity rarity;

    MonsterType(String name, int damage, int health, int mana, Rarity rarity) {
        this.name = name;
        this.damage = damage;
        this.health = health;
        this.mana = mana;
        this.rarity = rarity;
    }
}
